Allow multiple other dimensions in prewhiten data
PTB-MR/mrpro pull request #272
Opened 2024-04-17 16:12 UTC by fzimmermann89

and use triangular solve instead of torch.inv

2024-04-17 16:12 UTC, fzimmermann89 commented
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

2024-04-17 18:34 UTC, ckolbPTB requested changes

2024-04-17 18:34 UTC, ckolbPTB commented on tests/algorithms/test_prewhiten_kspace.py
> +    ns_k2k1k0 = (4, 5, 32)
n_k2k1k0 and n_other?

2024-04-17 18:34 UTC, ckolbPTB commented on tests/algorithms/test_prewhiten_kspace.py
> +    ns_other = (1,)
would make sense to test for n_other > 1 if this is the feature this PR adds

2024-04-17 23:19 UTC, fzimmermann89 commented on tests/algorithms/test_prewhiten_kspace.py
> +    ns_other = (1,)
🙈

2024-04-18 06:59 UTC, ckolbPTB approved these changes

2024-04-19 15:40 UTC, merged