Add addition of operator with tensor
PTB-MR/mrpro pull request #389
Opened 2024-09-04 19:06 UTC by ckolbPTB

closes #387

2024-09-05 21:14 UTC, fzimmermann89 commented
Do we want 
Operator + lambda to mean
a) (Operator+ lambda)(x)=Operator(x) + lambda(x) or
b) Operator(x) + lambda

For regularized reconstruction we will need a)

2024-09-05 21:17 UTC, fzimmermann89 commented
B) would not be a linear operator 

Something I realized after writing the code for it.... ...

2024-09-05 21:20 UTC, fzimmermann89 commented
And a)ight indeed br better served by a identity operator, see #390, last test.

2024-09-06 14:47 UTC, ckolbPTB commented on src/mrpro/operators/LinearOperator.py
> +        Returns lambda x: lambda x: self(x) + other
should this be self(x) + other*x (similar in line 176)?

2024-09-25 16:17 UTC, schuenke approved these changes
Just did a very very quick review, but lgtm and tests seem to work as expected.

2024-09-25 16:17 UTC, schuenke commented on src/mrpro/operators/LinearOperator.py
> +        Returns lambda x: lambda x: self(x) + other*x
one `lambda x:` to much?

2024-10-05 23:01 UTC, fzimmermann89 requested changes
Please hold with merge

2024-10-07 19:01 UTC, fzimmermann89 commented
This is one way to do it, via a separate (Linear)OperatorTensorSum class.
Alternativly, we could also reuse the IdentityOp:
LinOp + Tensor = LinOpSum(Op, Identity*Tensor), see #430

2024-10-15 21:40 UTC, closed without merging